name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - released
      - prereleased

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image-push:
    uses: ./.github/workflows/image-push.yml
    with:
      project: docs
    secrets: inherit

  upgrade-server:
    needs:
      - image-push
    uses: coscene-io/cicd-templates/.github/workflows/sub-chart-upgrade.yml@main
    with:
      deployment-name: coscene-docs
    secrets: inherit