# Deploy to https://docs.coscene.cn
name: Deploy
on:
  push:
    branches:
      - release
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node env
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Build Project
        run: |
          export NODE_OPTIONS=--max_old_space_size=5632
          pnpm install
          pnpm build

      - name: Setup OSS
        uses: coscene-io/setup-ossutil@v2
        with:
          endpoint: oss-cn-hangzhou.aliyuncs.com
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Deploy to OSS
        run: |
          ossutil rm -rf oss://${{ secrets.OSS_TARGET_BUCKET }}/
          ossutil cp -rf build/  oss://${{ secrets.OSS_TARGET_BUCKET }}/

      - name: Notification to Feishu
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL_RHODE_ISLAND }}
          msg_type: text
          content: |
            text: |
              A new version of coScene Docs site has been deployed at the bucket ${{ secrets.OSS_TARGET_BUCKET }}
              committer: ${{ github.actor }}
              URL: https://docs.coscene.cn
